language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'

services: mongodb

env:
  global:
    - MONGODB_URI_TEST= "mongodb://localhost/diary_test"

before_script:
  - sleep 15

script:
  - npm ci
  - npm test
after_success:
  - npm run coveralls
